apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: auto-playlist
spec:
  project: default
  source:
    repoURL: https://github.com/jkleve/auto-playlist
    path: cfgs/helm
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: auto-playlist
